# Create Role for pod security policy
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: developers
spec:
  privileged: false  # Don't allow privileged pods!
  # The rest fills in some required fields.
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
---
# Create Role for pod security policy
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: paul-user-pod-security-policy
  namespace: paul
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - developers
---
# Create RoleBinding
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: paul-user-pod-security-policy
  namespace: paul
subjects:
- kind: User
  name: paul # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: paul-user-pod-security-policy