# Create Namespace
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: paul
spec: {}
---
# Create Role
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: paul-user-full-access
  namespace: paul
rules:
- apiGroups: ["", "extensions", "apps", "kubeflow.org.v1beta1"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
# Create RoleBinding
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: paul-user-view
  namespace: paul
subjects:
- kind: User
  name: paul # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: paul-user-full-access