# Create Namespace
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: team1
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: team1-quota
spec:
  hard:
    cpu: 16
    memory: 10Gi
    pods: 1k
---
apiVersion: v1
kind: LimitRange
metadata:
  name: team1-limits
spec:
  limits:
  - default:
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: 2
      memory: 2Gi
    min:
      cpu: 10m
      memory: 10Mi
    type: Container
