apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view
  namespace: team1
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: team1-viewers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view
  namespace: team1
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]