#!/usr/bin/env bash

domain_name=${1:-}
if [ -z "${domain_name}" ] ; then
    echo "usage: $0 <domain name>"
    exit 1
fi

if [ -z "${NS1_API_KEY}" ] ; then
    echo "environmental variable NS1_API_KEY not set"
    exit 1
fi
echo "paste the following lines into the openvpn configuration file generated by packet.io API"
echo ""
echo "dhcp-option DOMAIN-ROUTE ${domain_name}"
for dns_name in `curl -s -X GET -H "X-NSONE-Key: ${NS1_API_KEY}" \
                 https://api.nsone.net/v1/zones/${domain_name}/${domain_name}/NS |\
                 jq -r '."answers"[] | ."answer"' 2>&1 | grep \" | awk -F '"' '{print $2}'`
do
    echo "dhcp-option DNS `host ${dns_name} | awk '{print $4}'`"
done